apiVersion: v1
kind: Service
metadata:
  name: world
  labels:
    app: world
    service: world
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  labels:
    app: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: world
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
