apiVersion: v1
kind: Service
metadata:
  name: auth-grpc
  labels:
    app: auth-grpc
    service: auth-grpc
spec:
  ports:
  - port: 5005
    name: tcp
  selector:
    app: auth-grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-grpc
  labels:
    app: auth-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-grpc
  template:
    metadata:
      labels:
        app: auth-grpc
    spec:
      containers:
      - name: auth-grpc
        image: auth-grpc
        imagePullPolicy: Never
        ports:
        - containerPort: 5005
